name: Update gist with WakaTime stats by myself
on: push
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 08e98bfd0854dd93df7ae4354a961ce2
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
